mobs:
  ZOMBIE:
    item: DIAMOND
    chance: 70
    disable-vanilla-loot: true
    custom-name: "&6Espada de &cFuego"
    lore:
      - "&7Esta es una línea de lore personalizada"
      - "&dCon soporte para colores hex y &!"
  SKELETON:
    item: EMERALD
    chance: 50
    disable-vanilla-loot: false
    custom-name: "&aGema Misteriosa"
    lore:
      - "&bEsta gema tiene poderes mágicos"
  CREEPER:
    item: NETHER_STAR
    chance: 5
    disable-vanilla-loot: true
    custom-name: "#FF5733Estrella Ardiente"
    lore:
      - "#FF0000Brilla intensamente como el fuego"