mobs:
  ZOMBIE:
    disable-vanilla-loot: true
    items:
      - item: DIAMOND_SWORD
        chance: 70
        custom-name: "&6Espada de &cFuego"
        lore:
          - "&7Esta es una línea de lore personalizada"
          - "&dCon soporte para colores hex y &!"
        quantity: 1
      - item: DIAMOND
        chance: 30
        custom-name: "&bDiamante Brillante"
        lore:
          - "&7Un diamante muy raro"
        quantity: 3
      - item: EMERALD
        chance: 50
        custom-name: "&aGema Misteriosa"
        lore:
          - "&bEsta gema tiene poderes mágicos"
      - item: GOLD_INGOT
        chance: 50
        custom-name: "&6Lingote Dorado"
        lore:
          - "&7Un lingote de oro puro"
        quantity: 2

  SKELETON:
    disable-vanilla-loot: false
    items:
      - item: EMERALD
        chance: 50
        custom-name: "&aGema Misteriosa"
        lore:
          - "&bEsta gema tiene poderes mágicos"
      - item: GOLD_INGOT
        chance: 50
        custom-name: "&6Lingote Dorado"
        lore:
          - "&7Un lingote de oro puro"

  CREEPER:
    disable-vanilla-loot: false
    items:
      - item: NETHER_STAR
        chance: 50
        custom-name: "#FF5733Estrella Ardiente"
        lore:
          - "#FF0000Brilla intensamente como el fuego"
      - item: TNT
        chance: 50
        custom-name: "&cCarga Explosiva"
        lore:
          - "&7¡Una carga explosiva lista para detonarse!"

  COW:
    disable-vanilla-loot: true
    items:
      - item: NETHER_STAR
        chance: 0.1
        custom-name: "#FF5733Estrella Ardiente"
        lore:
          - "#FF0000Brilla intensamente como el fuego"
      - item: TNT
        chance: 50
        custom-name: "&cCarga Explosiva"
        lore:
          - "&7¡Una carga explosiva lista para detonarse!"
